### ISSUE TITLE
Feature: Add task

### ISSUE THREAD

**Issue by ravishwetha** [CS2103AUG2016-F10-C3/main#10]
User is able to:
Add a new task with just a description

**Comment by ravishwetha** [comment]
A task can be added without the other details like due date, priority, location and tags. Need to keep in mind that we will be adding those.

**Comment by tessav** [comment]
Just a note: according to the tutor, there should be support for 3 types of tasks - floating tasks, event tasks (start date and end date), and deadline tasks. Start and end date should be included in the model.

**Comment by tessav** [comment]
Tasks can be added, description added in V0.4
