### ISSUE TITLE
Feature: Support for adding floating tasks

### ISSUE THREAD

**Issue by shaocloud** [CS2103AUG2016-F10-C3/main#20]
Floating tasks are tasks without any deadlines, although we should provide support for tasks missing every field except for title

**Comment by shaocloud** [comment]
I've managed to set it so that blank fields (i.e. setting variables to null) are ok but you still need to use 

`d/ a/ & p/`

 (haven't figured out how to set the regex to ignore those values and I don't want to mess it up)

**Comment by ravishwetha** [comment]
Which branch are you working on (or a fork)? That sounds like good progress nevertheless so you could make a PR and I'll test it out then merge.

**Comment by ravishwetha** [comment]
Also, since you have been able to work on the use-model.task branch without issue, I'll merge it to C3/base/gtd.

**Comment by shaocloud** [comment]
thanks! I'll PR and let you see, it's not complete but should work for now

**Comment by shaocloud** [comment]
@ravishwetha I've made a pull request (#31 Update main use-model.task...) against use-model.task, thanks! :)

**Comment by tessav** [comment]
all fields should be optional except name

**Comment by tessav** [comment]
Support for floating tasks largely done! I'll close this issue.
