### ISSUE TITLE
overhaul: shift person model to task model package

### ISSUE THREAD

**Issue by tessav** [CS2103AUG2016-F10-C3/main#23]
**task model** (**edit if needed**):
- task title (required)
- due date / time
- start date / time
- end date / time
- description
- location
- tags list
- priority

**Comment by ravishwetha** [comment]
#28 Incorporates Task Title (as Name), DueDate, Location (as Address), Priority and Tags with no unit test errors. Still pending Description, Start date and End date in this branch. Should we merge this branch, close issue and open the pending items as things we can work on together? I think adding the remaining 3 classes should be easier now (source code, xml files) and can be done individually (tests will still be tricky).
