### ISSUE TITLE
edit developer guide and user guide to reflect new model

### ISSUE THREAD

**Issue by tessav** [CS2103AUG2016-F10-C3/main#24]

**Comment by tessav** [comment]
Changed the command list in user guide (under C3/documentation/UserGuide branch), and made the user stories more comprehensive (under C3/documentation/DeveloperGuide branch). Can someone review the changes and merge if accurate? I will update the 'Features' section of the user guide once confirmed.

**Comment by ravishwetha** [comment]
I've merged them
