### ISSUE TITLE
Error test case in gtd base

### ISSUE THREAD

**Issue by NachosNLC** [CS2103AUG2016-F10-C3/main#36]
<img width="202" alt="capture4" src="https://cloud.githubusercontent.com/assets/21749671/19590156/f779a0d0-97a2-11e6-8956-b1a9cc583669.PNG">

**Comment by ravishwetha** [comment]
![screen shot 2016-10-27 at 9 06 49 pm](https://cloud.githubusercontent.com/assets/18163420/19768258/58f1b402-9c89-11e6-900b-d60f0be68211.png)

Hey I can't seem to replicate the error when I checkout the base branch, perhaps it's still a configuration issue following the "JRE System Library fix" for access restriction?

@shaocloud do you have the same error after fixing Access restriction errors?
