### ISSUE TITLE
Collate files

### ISSUE THREAD

**Issue by chanjunweimy** [CS2103AUG2016-F10-C3/main#45]
Hi everyone,

While you all are working hard in building the features, can you all try to collate the files first? So that I could give comments to you all... This is to help you improving your codes... :) 

Thank you.

Cheers,
Jun Wei

**Comment by ravishwetha** [comment]
#46 Ok I added the collate tool and generated two .md files, my own and code from the address book-level4. I did the initial refactoring but most of the work was just renaming files and variables so I didn't include that, it does not come under what the Handbook considers "significant writing effort" right?

**Comment by chanjunweimy** [comment]
@ravishwetha Hi I think you are right :)  where do you put your collate files to?
