### ISSUE TITLE
[Important] undo function

### ISSUE THREAD

**Issue by tessav** [CS2103AUG2016-F10-C3/main#58]
must be able to undo previous command (according to required features in project brief)

**Comment by shaocloud** [comment]
For reference: [http://www.javaworld.com/article/2076698/core-java/add-an-undo-redo-function-to-your-java-apps-with-swing.html](url)

**Comment by ravishwetha** [comment]
#61 self-tested, no Unit tests written yet so try it out for any possible bugs you have in mind
