### ISSUE TITLE
Code in master does not pass all test cases.

### ISSUE THREAD

**Issue by ravishwetha** [CS2103AUG2016-F10-C3/main#6]
16 test cases fail, all related to null assertions.

![screen shot 2016-10-14 at 12 32 21 am](https://cloud.githubusercontent.com/assets/18163420/19357800/bbc8b68c-91a5-11e6-84f7-550b52864cd6.png)

**Comment by ravishwetha** [comment]
![old c3 rename-packages all-test-cases pass](https://cloud.githubusercontent.com/assets/18163420/19377668/aea8283c-921a-11e6-875b-57c9b6df49b5.png)

Hey I've got the test cases to pass, could you try out my branch OLD-C3/superficial/change-package-names to see if they pass for you too? Be sure to enable assertions by going to Run Configurations -> Arguments -> type in -ea under VM arguments.

**Comment by tessav** [comment]
<img width="346" alt="screen shot 2016-10-15 at 6 27 21 pm" src="https://cloud.githubusercontent.com/assets/11312006/19409362/15bfd87c-9305-11e6-9214-f328245f7256.png">
Yup it doesnt have any errors! But hmm I think the errors and failures came from the configuring of person model to task model.

**Comment by ravishwetha** [comment]
Hey, I've looked through fixing the errors on the master but after a good two hours I was only able to fix one failure in the master code by changing all instances of '/p', '/e' and '/a' to '/d', '/m' and '/l' as you had only changed this in the generateAddCommand function of LogicManagerTest but not elsewhere. I was eager on resolving this because I wanted to start on the other issues for the milestone we set for this week with a base code in the master that passed all test cases. I'm really quite stumped why there are errors in the master as I saw no apparent difference in the code with my branch since I pretty much did what you had done other than changing the output strings in the tests that don't really effect anything (I made sure by changing it around, also are a good touch) and the dml prefixes instead of pea which as discussed before was only related to the execute_add_invalidPersonData failure. 

So how about we make the OLD-C3/superficial... branch the master and save this version of master in another branch? I'll do it with approval from one other person and we can close this issue?

Edit: I couldn't find anything that I'd attribute to task model, it has not been involved in the tests and seems isolated just as it is in my branch (from file searching for model.task in both branches), is there a location where you've used our new package? On it's own, it doesn't have compilation issues either.

**Comment by tessav** [comment]
Sure, we can just use the OLD-C3/superficial... branch if it's easier for you to make changes! By task model, I didn't mean using the new model package but changing the messages, email regex etc. What will you be working on first if we were to switch back to the old branch? (so that I know what else I can help with)

**Comment by tessav** [comment]
I've added a project in this repo so that we can all keep track of what each other is working on at the moment (to prevent duplicate work and if we have any questions we know who to ask). @ravishwetha maybe you can add what you'll be working on first?

**Comment by ravishwetha** [comment]
Ok cool, I would like to work on the edit command.
