### ISSUE TITLE
tutor feedback

### ISSUE THREAD

**Issue by tessav** [CS2103AUG2016-F10-C3/main#64]
- explain why need a map (match with user needs, whatever design you have, you need to justify)
- hide browser if 'none'
- edit a few fields at the same time 
- delete 1,2,3,4
- when typing other things, browser still shows deck
- prepare 50 tasks
- reflect a change (auto highlights the particular task)
- UI color coding of tasks

**Comment by ravishwetha** [comment]
Also, I think it's unclear the differences between list and find

**Comment by tessav** [comment]
i think "list" is showing the default task list panel (with all the tasks), while find is filtering and searching for a single task / group of tasks.
